include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [ build/** ]
  language:
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    prefer_single_quotes: true
    slash_for_doc_comments: true
    comment_references: true
    package_api_docs: true
    public_member_api_docs: true
